[theme]
# Primary accent color for interactive elements.
primaryColor = "f183cb"

# Background color for the main content area (Cor de Fundo).
backgroundColor = "#050733"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "595eed"

# Color used for almost all text.
textColor = "#ffffff"